%TC:macro \del [ignore]

Models of the spread of disease in a population often make the simplifying
assumption that the population is homogeneously mixed, or is divided into
homogeneously mixed compartments. However, human populations have complex
structures formed by social contacts, which can have a significant influence on
the rate \add{and pattern} of epidemic spread. Contact \del{network models}
\add{networks} capture this structure by explicitly representing each contact
that could possibly lead to a transmission. \add{Contact network models
parameterize the structure of these networks, but estimating their parameters
from contact data requires extensive, often prohibitive, epidemiological
investigation.}

We developed a method based on approximate Bayesian computation (ABC) for
estimating structural parameters of the contact network underlying an
observed viral phylogeny. The method combines adaptive sequential Monte Carlo
for ABC, Gillespie simulation for propagating epidemics though networks, and a
\add{previously developed} kernel-based tree similarity score. \add{Our method
offers the potential to quantitatively investigate contact network structure
from phylogenies derived from viral sequence data, complementing traditional
epidemiological methods.}

We applied our method to \del{fit} the Barab\'{a}si-Albert network model.
\add{This model incorporates the preferential attachment mechanism observed in
real world social and sexual networks, whereby individuals with more
connections attract new contacts at an elevated rate (``the rich get
richer'').} \del{to simulated transmission trees and applied it to viral
phylogenies estimated from six real-world HIV sequence datasets.} Using
simulated data, we found that the strength of preferential attachment and the
number of infected nodes could often be accurately estimated. However, the mean
degree of the network and the total number of nodes appeared to be weakly- or
non-identifiable with ABC. 

<<alpha, include=FALSE>>=
    source("global.R") 
    d <- setDT(collect.data("../../simulations/aggregates/hpd/*"))
    d <- d[m_min == 1 & agg_gene == "gag",]

    stopifnot(d[parameter == "alpha", dataset[which.min(mean)]] == "cuevas2009")
    stopifnot(d[parameter == "alpha", dataset[which.max(mean)]] == "zetterberg2004")

    stopifnot(d[parameter == "alpha", max(mean)] >= 0.9)
    stopifnot(d[parameter == "alpha", max(mean)] < 1.0)
@

Finally, the Barab\'{a}si-Albert model was fit to \del{six}\add{eleven} real
world HIV datasets, and substantial heterogeneity in the parameter estimates
was observed. \del{Point estimates} \add{Posterior means} for the preferential
attachment power \add{were all sub-linear, consistent with literature results.
We found that the strength of preferential attachment was higher in injection
drug user populations, potentially indicating that high-degree
``superspreader'' nodes may play a role in epidemics among this risk group.}
Our results underscore the importance of considering contact structures when
\del{performing phylodynamic inference}\add{investigating viral outbreaks.}
