<<setup, include=FALSE>>=
    source("global.R")
@

\label{sec:disc}

\subsection{\software{Netabc}: uses, limitations, and possible extensions}

\glsreset{ER}
\glsreset{WS}

Contact networks can have a strong influence on epidemic progression, and are
potentially useful as a public health tool~\autocite{wang2015targeting,
little2014using}. Despite this, few methods exist for investigating contact
network parameters in a phylodynamic framework \autocite[although see][for
related work]{groendyke2011bayesian, volz2008sir, brown2011transmission,
leventhal2012inferring, greenbaum2016inference}. Kernel-ABC is a model-agnostic
method which can be used to investigate any quantity that affects tree
shape~\autocite{poon2015phylodynamic}. In this work, we developed
\software{netabc}, a method based on kernel-ABC to infer the parameters of a
contact network model. The method \del{is general, meaning that it} can be used
to infer parameters of any network model, as long as it allows simulated
networks to be easily generated. We have included generators for the \gls{BA}
model discussed here, as well as the \gls{ER}~\autocite{erdos1960evolution} and
\gls{WS}~\autocite{watts1998collective} network models.  Instructions for
adding additional models are available in the project's online documentation.
We have made \software{netabc} publicly available at
\url{github.com/rmcclosk/netabc} under a permissive open source license, to
encourage other researchers to apply and extend our method.

Several alternative network models and modelling frameworks have been developed
which may provide useful future targets for \gls{ABC}. Waring
models~\autocite{irwin1963place,handcock2004likelihood} are a more flexible
type of preferential attachment model which permit a subset of attachments to
be formed non-preferentially. These models were used by
\textcite{brown2011transmission} to characterize the transmission network in
the United Kingdom. \Glspl{ERGM}~\autocite{robins2007introduction} are a
flexible and expressive parameterization of contact networks in terms of
statistics of network features such as pairs and triads.
\textcite{goodreau2006assessing} evaluated the effect of several different
\gls{ERGM} parameterizations on transmission tree shape and effective
population size, and suggested the use of \glspl{ERGM} as a general framework
for estimation of epidemiological quantities related to \gls{HIV} transmission.
Except for a few special cases, simulating a network according to an \gls{ERGM}
generally requires \gls{MCMC}, which would be too computationally intensive to
integrate into \software{netabc} as it currently stands. To fit \gls{ERGM} with
\gls{ABC}, one possibility would be to consider the network
itself as a parameter to be modified by the \gls{MCMC} kernel.  Other network
modelling frameworks include the partnership-centric formulation developed
by~\textcite{eames2002modeling} and the log-linear adjacency matrix
parameterization applied by~\textcite{morris1993epidemiology}.

The two-step process of simulating a contact network and subsequently allowing
an epidemic to spread over that network carries with it the assumption that the
contact network is static over the duration of the epidemic. Clearly this
assumption is false, as people make and break partnerships on a regular basis.
Addressing the impact of this simplifying assumption is outside the scope of
this work. However, the same assumption is made by most studies using contact
network models in an epidemiological context~\autocite{welch2011statistical,
bansal2007individual}. In principle, \gls{ABC} could be adapted
to dynamic contact networks by using a method such as that developed by
\textcite{robinson2012dynamics} to simulate such a network, while concurrently
simulating the spread of an epidemic.

It is important to note that \software{netabc} takes a transmission tree as
input, rather than a viral phylogeny. In reality, true transmission trees are
not available and must be estimated; these estimates are often based on the
viral phylogeny. Although this has been demonstrated to be a fair
approximation~\autocite[e.g.][]{leitner1996accurate}, and is frequently used in
practice~\autocite[e.g.][]{stadler2013uncovering}, the topologies of a viral
phylogeny and transmission tree can differ
significantly~\autocite{ypma2013relating, hall2015epidemic} due to within-host
evolution and the sampling process. We have left the estimation of a
transmission tree up to the user. In theory, it is possible to incorporate the
process by which a viral phylogeny is generated along with a transmission tree
into our method, for example by simulating within-host dynamics. \add{Indeed,
progress has very recently been demonstrated on this front in a talk by
\textcite{giardina2016inference}, who have independently developed in a method
similar to ours to fit contact network models to phylogenetic data that
additionally incorporates a within-host evolutionary model.} Although this may
be an avenue for future extension, we felt that it would obscure the primary
purpose of this work, which is to study contact network parameters. In
addition, there are a number of different methods available for inferring
transmission trees~\autocite{didelot2014bayesian, ypma2012unravelling,
jombart2011reconstructing, cottam2008integrating, hall2015epidemic}, some of
which incorporate geographic and/or epidemiological data not accommodated by
our method. We therefore felt it would be best to allow researchers to use
their own preferred method of constructing a transmission tree.

Our implementation of \gls{SMC} uses a simple multinomial scheme to sample
particles from the population according to their weights. Several other
sampling strategies have been developed~\autocite{douc2005comparison}, and it
is possible that the use of a more sophisticated technique might increase the
algorithm's accuracy. Finally, the \gls{ABC}-\gls{SMC} algorithm is
computationally intensive, taking about a day when run on 20 cores in parallel
with the settings described in the methods section. Implementing
parallelization using \gls{MPI}, rather than \gls{POSIX} threads as we have
done here, would allow the program to be run over a larger number of cores on
multiple CPUs in parallel.

\subsection{Analysis of \acrlong{BA} model with synthetic data}

The preferential attachment power \gls{alpha} had a very strong influence on
tree shape in the range of values we considered
(\cref{fig:alphatrees,fig:kpca}). Although the tree kernel was the most
effective classifier for \gls{alpha}, a Sackin's index of tree imbalance
performed nearly as well (\cref{fig:rsquared}). This result was intuitive: high
\gls{alpha} values produce networks with few well-connected ``superspreader''
nodes which are involved in a large number of transmissions, resulting in a
highly unbalanced ladder-like tree structure (\cref{fig:alphatrees}). 
\del{There was no observable bias in the estimates of \gls{alpha} obtained with
\software{netabc}, however the variation in these estimates
was higher for $\alpha < 1$ than for $\alpha \geq 1$} \add{There appeared to be
weaker identifiability for \gls{alpha} $<$ 1 than for \gls{alpha} $\geq$ 1}
(\cref{fig:abcptm2,tab:abchpd}), which may be partially explained by the
relationship between \gls{alpha} and the power law exponent \gls{gamma}
(\cref{fig:gamma}). \add{Although the degree distributions do not truly follow
a power law for $\gls{alpha} \neq 1$, the fitted exponent still captures the
slope of the degree distribution reasonably well (\cref{fig:powerlaw}), and 
distributions with similar fitted \gls{gamma} values appear qualitatively
similar in other respects.} The \gls{gamma} values fitted to $\gls{alpha} = 0$
and $\gls{alpha} = 0.5$ are nearly identical (about $2.28 for \gls{alpha} = 0$
and $2.33 for \gls{alpha} = 0.5$ with $\gls{N} = 5000$ and $\gls{m} = 2$). In
other words, the degree distributions of networks with \gls{alpha} $< 1$ are
similar to each other, which may result in similarity of corresponding
transmission trees as well. 

The \gls{I} parameter, representing the prevalence at the time of sampling, was
also generally identifiable, although it was slightly over-estimated for both
cases we considered with \gls{ABC}. \add{Sackin's index was better able to
capture the effect of \gls{I} on tree shape than the \gls{nltt}
(\cref{fig:rsquared,fig:Icrossv}), suggesting that this parameter impacts the
distribution of branching times in the tree more than the topology. In a
homogeneously-mixed population, branching times can be modelled by the
coalescent process~\autocite{kingman1982coalescent}, in our case under the
\gls{SI} model~\autocite{volz2009phylodynamics}. Although our populations are
not homogeneously mixed, the forces which affect the distributions of branching
times still apply.} \del{The dynamics of the \gls{SI} model, and the coalescent
process, offer a potential explanation for the identifiability of \gls{I}.} In
our simulations, we assumed that all discordant edges shared the same
transmission rate, so that the waiting time until the next transmission in the
entire network was always inversely proportional to the number of discordant
edges. In the initial phase of the epidemic, when \gls{I} is small, each new
transmission results in many new discordant edges. Hence, there is an early
exponential growth phase, producing many short branches near the root of the
tree. As the epidemic gets closer to saturating the network, the number of
discordant edges decays, causing longer waiting times. \del{The distribution of
coalescence times in the tree should therefore be informative about \gls{I}.
This information is captured by the tree kernel, and also by the \gls{nltt}
statistic, which both performed quite well in classifying \gls{I}
(\cref{fig:rsquared}).}

The number of nodes in the network, \gls{N}, exhibited the most variation in
terms of its effect on tree shape. There was almost no difference between trees
simulated under different \gls{N} values when the number of infected nodes
\gls{I} was small (\cref{fig:Nkpca,fig:Ncrossv}). There is an intuitive
explanation for this result, namely that adding additional nodes does not
change the edge density or overall shape of a \gls{BA} network. \add{In fact,
this is why the degree distributions of these networks are called
``scale-free.''} This can be illustrated by imagining that we add a small
number of nodes to a network after the epidemic simulation has already been
completed. It is possible that none of these new nodes attains a connection to
any infected node. Thus, running the simulation again on the new, larger
network could produce the exact same transmission tree as before. On the other
hand, when \gls{I} is large relative to \gls{N}, the coalescent dynamics
discussed above also apply. The waiting times until the next infection
increase, resulting in longer coalescence times toward the tips. The relative
accuracy of the \gls{nltt} in these situations
(\cref{fig:rsquared,fig:Ncrossv}) corroborates this hypothesis, as the
\gls{nltt} uses only information about the coalescence times. When all \gls{BA}
parameters were simultaneously estimated with \gls{ABC}, \gls{N} was nearly
always over-estimated by approximately a factor of two
(\cref{fig:abcptm2,tab:abchpd}). One factor which may have contributed to this
bias was our choice of prior distribution. Since the prior for \gls{I} and
\gls{N} was jointly uniform on a region where $I \leq N$, more prior weight was
assigned to higher \gls{N} values. Another contributing factor relates to the
dynamics of the \gls{SI} model and the coalescent process and is discussed
below.

\gls{I} and \gls{N} were both systematically over-estimated by
\software{netabc}, although the bias was more severe for \gls{N} than for
\gls{I}. The number of infected individuals follows a logistic growth curve
under the \gls{SI} model. This kind of growth curve has three qualitative
phases: a slow ramp-up, an exponential growth phase, and a slow final phase
when the susceptible population is almost depleted. The waiting times until the
next transmission, which determine the coalescence times in the tree, are
dependent on the growth phase of the epidemic. Therefore, we hypothesize that
it is the growth phase at the time of sampling which most affects tree shape,
rather than the specific values of \gls{I} or \gls{N}. To investigate this
hypothesis, we simulated transmission trees over networks on a grid of \gls{I}
and \gls{N} values in the region of uniform prior density. We fit logistic
growth curves to the proportion of infected individuals over time, and
calculated the first and second derivatives of these curves (with respect to
time) at the time of transmission tree sampling. These derivatives give us an
indication of the growth rates of the epidemics at the time of sampling. As
shown in \cref{fig:derivs}, there are bands along which both derivatives are
similar which contain the values we tested. These bands span mostly higher
values of \gls{N} and \gls{I} than the true values. Therefore, if \gls{N} and
\gls{I} are free to vary (as is the case in \gls{ABC}), and our hypothesis is
true, both parameters will tend to be overestimated due to being less
identifiable within their own band. However, when \gls{N} is fixed at 5000, the
derivatives vary substantially along the \gls{I}-axis, which explains why
the grid search estimates of \gls{I} were accurate and unbiased
(\cref{fig:gridest,fig:gridptI}). \add{We also note the resemblance of the
contour surface of \cref{fig:derivs} to the two-dimensional marginal posterior
distributions on \gls{I} and \gls{N} obtained with simulated data
(\cref{fig:abclow2,fig:abchigh2}). In addition, both the accuracy and precision
of the \gls{ABC} estimates of \gls{I} improved substantially when \gls{N} was
marginalized out (\cref{fig:marginal}).}

\begin{figure}[ht]
  \centering
  \includegraphics{derivatives.pdf}
  \caption[
    First and second time derivatives of epidemic growth curves at time of
    sampling for various values of $I$ and $N$.
  ]{
    First and second \add{time} derivatives of epidemic growth curves at time
    of sampling for various values of \gls{I} and \gls{N}. Networks were
    simulated under the \gls{BA} model with \gls{alpha} = 1.0, \gls{m} = 2, and
    \gls{N} varied along the values shown on the $x$-axis. Transmission trees
    were sampled at the time when \gls{I} nodes were infected ($y$-axis).
    Logistic growth curves were fit to epidemic trajectories derived from the
    transmission trees, and their first and second derivatives were calculated
    at the time of sampling. Contours show first derivatives, while colours
    indicate second derivatives. Values of \gls{I} and \gls{N} used in
    simulation experiments with \gls{ABC} are indicated by diamonds.
  }
  \label{fig:derivs}
\end{figure}

The \gls{m} parameter, which controls the number of connections added to the
network per vertex, did not have a measurable impact on tree shape and was not
identifiable with \gls{ABC}, \add{nor with grid search when the other
parameters were held fixed.} The exception to this was the value \gls{m} = 1,
which produces networks without cycles whose associated trees were more easily
distinguished (\cref{fig:gridest,fig:gridm}). However, all the analyses
presented here did not take the absolute size of the transmission trees into
account, as the branch lengths were rescaled by their mean. Because higher
\gls{m} values imply higher edge density, an epidemic should spread more
quickly for higher \gls{m} than lower \gls{m} with the same per-edge
transmission probability.  Hence, considering the absolute height of the trees
may improve our method's ability to reconstruct \gls{m}. \add{It was also
pointed out to us by an anonymous reviewer that for a fixed \gls{I}, an
infected node may only end up transmitting along a fraction of its outgoing
edges, which could mask the presence of the extra edges associated with higher
\gls{m}}.

In addition to the tree height, many summary statistics have been developed to
capture particular details of tree shape~\autocite{bortolussi2006aptreeshape}.
Two of these, Sackin's index and the ratio of internal to terminal branch
lengths, were correlated with every \gls{BA} parameter. Classifiers based on
Sackin's index and the \gls{nltt} similarity measure performed well in some
cases, though poorly in others. \Gls{ABC} is often applied using a vector of
summary statistics~\autocite{marin2012approximate, sunnaaker2013approximate},
rather than a kernel-based similarity score as we have done here. Methods have
been developed to select an optimal combination of summary statistics for a
given inference task~\autocite{fearnhead2012constructing}. Hence, an avenue for
future improvement of our method may be the inclusion of additional summary
statistics to supplement the tree kernel. In addition, all four \gls{BA}
parameters were more accurately classified when the number of tips in the
transmission trees was larger, underscoring the importance of adequate sampling
for accurate phylodynamic inference~\autocite{novitsky2014impact}.

For \del{the more identifiable parameters}\add{\gls{alpha} and \gls{I}}, the
credible intervals attained from the marginal \gls{ABC} target distributions
were \del{much} narrower than those obtained through grid search\del{, while
point estimates were of comparable accuracy}. This was likely due to the fact
that \gls{SMC} employs importance sampling to approximate the posterior
distribution, while grid search simply calculates a distance metric which may
not have any resemblance to the posterior. Our method of finding credible
intervals from kernel scores along the grid, by normalizing the scores to
resemble a probability distribution, was somewhat ad hoc, which may also have
played a role. Regardless, this result indicates that there is benefit to
applying the more sophisticated method, even if values for some of the
parameters are known \textit{a priori}, and especially if credible intervals
are desired on the parameters of interest.

As noted by \textcite{lintusaari2016identifiability}, uniform priors on model
parameters may translate to highly informative priors on quantities of
interest. We observed a non-linear relationship between the preferential
attachment power \gls{alpha} and the fitted power law exponent \gls{gamma}
(\cref{fig:gamma}, although see the discussion in \cref{subsec:pa}). Therefore,
placing a uniform prior on \gls{alpha} between 0 and 2 is equivalent to placing
an informative prior that \gls{gamma} is close to 2. If we were primarily
interested in \gls{gamma} rather than \gls{alpha}, a more sensible choice of
prior might have a shape informed by \cref{fig:gamma} and be bounded above by
approximately $\gls{alpha} = 1.5$. This would bound \gls{gamma} in the region
$2 \leq \gls{gamma} \leq 4$ commonly reported in the network
literature~\autocite{liljeros2001web, schneeberger2004scale, colgate1989risk,
clemenccon2015statistical, brown2011transmission}. We note however that
\textcite{jones2003assessment} estimated \gls{gamma} values greater than four
for some datasets, in one case as high as 17, indicating that consideration of
a wider range of permitted \gls{gamma} values may be warranted.

The combination of method, model, and priors we employed did not produce
perfect estimates of any of the parameters. The estimates of \gls{alpha} were
the most accurate, although the variance of the estimates was high and the
confidence intervals were wide for $\gls{alpha} < 1$
(\cref{tab:abchpd,fig:abcptm2,fig:abcptm3,fig:abcptm4}). The estimates of
\gls{N} and \gls{I} were both upwardly biased, and the estimates of \gls{m}
were largely uninformative. Despite these limitations, a major result of our
investigation is that some contact network parameters have a measurable impact
on tree shape which can be used to perform statistical inference. Further
refinements to \software{netabc}, as well as the use of more sophisticated
network models, may improve the accuracy and precision of these estimates.

\subsection{Application to real world HIV data}

Our investigation of published HIV datasets indicated heterogeneity in the
contact network structures underlying several distinct local epidemics. When
interpreting these results, we caution that the \gls{BA} model is quite simple
and most likely misspecified for these data. In particular, the average degree
of a node in the network is equal to $2\gls{m}$, and therefore is constrained
to be a multiple of 2. Furthermore, we considered the case $\gls{m} = 1$, where
the network has no cycles, to be implausible and therefore assigned it zero
prior probability in one set of analyses. This forced the average degree to be
at least four, which may be unrealistically high for sexual networks. The fact
that the estimated values of \gls{alpha} differed substantially for several
datasets depending on whether or not $\gls{m} = 1$ was allowed by the prior is
further evidence of this potential misspecification. However, we note that for
two of the datasets, the estimated values of \gls{alpha} did not change much
between priors, and the estimates of $\gls{I}$ were robust to the choice of
prior for all datasets studied. More sophisticated models, for example models
incorporating heterogeneity in node behaviour, are likely to provide a better
fit to these data.

\del{With respect to the preferential attachment power $\alpha$, the six
datasets analyzed fell into two categories (\cref{fig:abchpd}). First, we
estimated a preferential attachment power close to 1, indicating linear
preferential attachment, for the BC data and the outbreaks studied by
\textcite{niculescu2015recent} and \textcite{wang2015targeting}. These
values were robust to specifying different priors for $m$. All three datasets
were sampled from populations in which we would expect a high degree of
epidemiological relatedness: \textcite{niculescu2015recent} studied a
recent outbreak among Romanian \gls{IDU}, \citeauthor{wang2015targeting}
sampled acutely infected MSM in Beijing, China, and the BC data
constituted a phylogenetic \gls{IDU} cluster. These are all contexts in which
we would expect some of the assumptions of the BA model, such as a connected
network, relatively high mean degree, and preferential attachment dynamics, to
hold.}

\del{The remaining three datasets (\textcite{cuevas2009hiv, novitsky2014impact,
li2015hiv}) had estimated values of $\alpha$ below 0.5 when $m = 1$ was
included in the prior, but these were not robust to changing the prior to
exclude $m = 1$. For the \citeauthor{cuevas2009hiv} data, model
misspecification is likely partially responsible. While the authors found that
a large proportion of the samples were epidemiologically linked, these were
mainly in small local clusters rather than the single large component
postulated by the BA model. In addition, the mixed risk groups in the dataset
would be unlikely to significantly interact, further weakening any global
preferential attachment dynamics. The dataset studied by
\textcite{novitsky2014impact} originated from a densely sampled population
where the predominant risk factor was believed to be heterosexual exposure.
Although the MAP estimate of $\alpha$ was almost unchanged when the value $m =
1$ was excluded from the prior, the confidence interval shrank substantially.}

<<disc, include=FALSE>>=
    source("global.R")
    d <- setDT(collect.data("../../simulations/aggregates/hpd/*"))
    d <- d[agg_gene == "gag"]
    d1 <- d[m_min == 1]
    d2 <- d[m_min == 2]
@

\subsubsection{Preferential attachment power is sub-linear and higher for \gls{IDU}}

\add{For all datasets we examined, the posterior mean estimates for \gls{alpha}
were sub-linear, ranging from 
    \Sexpr{d[m_min == 1 & parameter == "alpha", round(min(mean), 2)]}
to 
    \Sexpr{d[m_min == 1 & parameter == "alpha", round(max(mean), 2)]}.
The sub-linearity is consistent with the results of
\textcite{de2007preferential}, who developed a statistical inference method to
estimate the parameters of a more sophisticated \acrlong{PA} model
incorporating heterogeneous node behaviour. When used to analyze
population-level longitudinal partner count data, they found \gls{alpha} values
ranging from 0.26 to 0.62 depending on the gender and time period considered.
Our estimates of \gls{alpha} for the IDU/Romania was above this range under
both priors, as were the estimates for the MSM/Beijing data and the BC data
when $\gls{m} = 1$ was disallowed by the prior. The dataset investigated by
\textcite{de2007preferential} was derived from a survey of a random sample of
the Norwegian population, whereas our investigation focused on datasets from
known phylogenetic or geographic clusters of \gls{HIV}-infected persons. It is
therefore unsurprising that we detected stronger \acrlong{PA} dynamics in some
cases. For instance, random sampling is much less likely to discover the
high-degree nodes characterizing the tail of the degree distribution, simply
because those individuals are rare in the general population. In addition, it
is plausible that \gls{HIV}-positive individuals are more likely to be highly
connected in their sexual networks, as the odds of acquiring \gls{HIV} increase
with the number of unprotected sexual contacts.}

\add{Both \textcite{de2007preferential} and the HET/Botswana data studied
populations whose primary risk factor for \gls{HIV} infection was heterosexual
contact. \citeauthor{de2007preferential} explicitly excluded reported
homosexual contacts; \citeauthor{novitsky2014impact} did not, but noted that
heterosexual contact is the primary mode of transmission in Botswana where the
study was done. In the first of the two papers describing the Botswana
study~\autocite{novitsky2013phylogenetic}, the authors noted that their sample
was gender-biased, being composed of approximately 75\% women. Our estimate of
\gls{alpha} for these data was 
    \Sexpr{d[m_min == 1 & dataset == "novitsky2014" & parameter == "alpha", round(mean, 2)]}
        or 
    \Sexpr{d[m_min == 2 & dataset == "novitsky2014" & parameter == "alpha", round(mean, 2)]},
depending on the prior on \gls{m}. Similarly, \textcite{de2007preferential}
estimated 0.54, 0.57, and 0.29 for 3-year, 5-year, and lifetime partnership
networks respectively for the female portion of their sample.}

\add{For both choices of prior on \gls{m}, the datasets derived from \gls{IDU}
populations had a higher estimated \acrlong{PA} power than the other datasets
(\cref{fig:abchpd,fig:abchpdm2}). This finding is in line with
\textcite{dombrowski2013topological}, who reanalyzed a network of \glspl{IDU}
in Brooklyn, USA, collected between 1991 and
1993~\autocite{friedman2006social}. They found that the \gls{IDU} network
resembled a \gls{BA} network much more closely than other social and sexual 
networks, and offered sociological explanations for the apparent \acrlong{PA}
dynamics in this population. Importantly, from a public health perspective,
the authors asserted that the removal of \emph{random} individuals from
\gls{IDU} networks may have the paradoxical effect of increasing the network's
epidemic susceptibility. When low-degree nodes are removed, as would occur
during a police crackdown, their network neighbours may turn to well-known
community members for advice or supplies, thus increasing the connectivity of
these high-degree nodes.}

\add{Unfortunately, the sub-linear region for \gls{alpha} identified by both
\textcite{de2007preferential} and \software{netabc} is also the region of
poorest identifiability (\cref{fig:gridest,fig:abcptm2}). This was reflected in
the high level of uncertainty in the estimates, with most 95\% \gls{HPD}
intervals covering the majority of the range [0, 1]. The value $\gls{alpha} =
0.5$ was contained in the 95\% \gls{HPD} interval for every dataset;
consequently, it is not possible to say with high confidence that any of the
\gls{alpha} values are different from each other. In synthetic data, the
confidence intervals around \gls{alpha} narrowed when other parameters were
marginalized out (\cref{fig:marginal}). Thus, it is possible that estimates of
\gls{alpha} could be made more precise by specifying either exact values or
informative priors on the other \gls{BA} parameters. We argued informally in
\cref{subsec:whyba} that \gls{I}, \gls{m}, and \gls{N} can sometimes be
estimated by standard epidemiological methods, although the difficulty may
depend on the specific epidemic under consideration.}

\subsubsection{Power law exponent is within reported range, but hard to interpret}

\add{In order to compare our results to existing literature on networks and
distributions of partner counts, we have reported estimated values for the
power law exponent \gls{gamma} of the real data sets we evaluated. However, the
posterior means for \gls{alpha} for all six datasets were less than one; the
degree distributions in this parameter range are stretched exponential, not
power law~\autocite{krapivsky2000connectivity}. As we show in
\cref{fig:powerlaw}, the power law fit does capture the slope of the degree
distribution fairly well, but the results should still be interpreted
cautiously. \textcite{krapivsky2000connectivity} showed that the power law
distribution can be maintained, with \gls{gamma} tuned to any desired value, by
a straightforward modification of the \gls{BA} model. The authors define the
``connection kernel'' $A_k$ the probability of a new connection to a node of
degree $k$, up to a normalizing constant. In the \gls{BA} model as we have
presented it here, $A_k = k^{\alpha} + 1$. Taking $A_k$ as any asymptotically
linear function will result in a power law distribution, with the exponent
\gls{gamma} determined by the properties of $A_k$. Implementing such a model
would be straightforward and seems a natural next step toward improving the
realism of the \gls{BA} model.}

\add{\Cref{tab:litgamma} shows some estimated \gls{gamma} values reported in the
network literature.  Our estimates are most similar to those of
\textcite{liljeros2001web, rothenberg2007large}, but interpretation of the
exact values is challenging. Estimates from the literature mainly fall between
2 and 4, although substantial variation within this range exists, even for
networks with apparently similar demographics. For example,
\textcite{schneeberger2004scale} estimate higher \gls{gamma} values for
heterosexual females than heterosexual males, while
\textcite{clemenccon2015statistical} find the opposite. Some of these
differences are likely due to the differing time intervals considered in each
study -- some investigate the distribution of lifetime partners, while others
consider only recent partnerships, such as in the past year. However, the
effect of the time period on \gls{gamma} is not readily obvious from the
available estimates.}

\begin{table}[ht]
    \centering
    \input{\tablepath/lit-gamma}
    \caption[
        Values of power law exponent \gls{gamma} previously reported in the
        literature.
    ]{
        Values of power law exponent \gls{gamma} previously reported in the
        literature. In the risk group column, ``mixed sexual'' indicates
        participants were not selected on the basis of sexual orientation;
        these values likely reflect primarily heterosexual dynamics.
        \textcite{brown2011transmission} studied a phylogenetically estimated
        transmission network, rather than a contact network.
        The values presented by \textcite{jones2003assessment} were in the
        context of arguing that the power law distribution is not suitable for
        use with network data.
    }
    \label{tab:litgamma}
\end{table}

\subsubsection{HIV prevalence estimates are often discordant with epidemiological information}

\add{The true \gls{HIV} prevalence in a population can be
difficult to estimate for several reasons. \gls{HIV}-infected individuals may
be asymptomatic for months or years, possibly delaying their awareness of their
status. In many contexts, the risk factors for acquisition of \gls{HIV} are
illegal or stigmatized, which may represent a barrier to testing, treatment,
and/or disclosure of status. Several of the studies whose data we analyzed
report the number of new infections over the study period. We expect these
numbers to be lower, perhaps substantially, than the true prevalence. We also
note that our simulation study showed that the estimates of \gls{I} obtained
with \software{netabc} were upwardly biased, the severity increasing with the
true value of \gls{I}. In addition, our initial exploratory analysis showed
that the identifiability of \gls{I} decreases with the number of sampled tips 
(\cref{fig:Icrossv,fig:Ikpca}). In real world studies, the proportion of
infected individuals sampled is usually low, which may impede our ability to
estimate \gls{I}. In the following, we discuss any information available about
the \gls{HIV} prevalence in the analyzed study populations, and relate this to
our estimates. However, due to the aforementioned challenges, this information
cannot be taken as absolute ``ground truth''. Discrepancies between our results
and the available data may indicate that the estimates produced by
\software{netabc} are inaccurate, but they may also indicate that the available
epidemiological data was not sufficient to estimate the true prevalence. Since
the estimates of \gls{I} were largely robust to the choice of prior on \gls{m}
(\cref{fig:abchpd,fig:abchpdm2}), we discuss here only the results obtained
with the prior $\gls{m} \sim \DiscreteUniform(1, 5)$.}

\add{The prevalence estimates for two \gls{IDU} epidemics in Eastern Europe,
IDU/Romania and IDU/Estonia, were 
    \Sexpr{d1[dataset == "niculescu2015" & parameter == "I", round(mean)]} and 
    \Sexpr{d1[dataset == "zetterberg2004" & parameter == "I", round(mean)]}.
The authors of the IDU/Romania study~\autocite{niculescu2015recent} reported
that 494 new \gls{HIV} infections were diagnosed among the studied population
(\glspl{IDU} in Bucharest) during the study period, and this value was
contained in our 95\% \gls{HPD} interval
    (\Sexpr{d1[dataset == "niculescu2015" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "niculescu2015" & parameter == "I", round(hpd.max.95)]}).
On the other hand, the IDU/Estonia data were collected from several locations
in the country. Using their reported incidence estimates, there were
approximately 2000 new infections in the country during the study period, a
value outside our 95\% \gls{HPD} interval
    (\Sexpr{d1[dataset == "zetterberg2004" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "zetterberg2004" & parameter == "I", round(hpd.max.95)]}).
The authors indicated that their sample was ``convenience based''; it is
possible that other, harder-to-reach individuals had no contacts with those
sampled, reducing the apparent network size. In contrast, the IDU/Canada data
was collected primarily from \gls{IDU} in Vancouver's downtown east side, a
population that has been intensively targeted by public health interventions.
Combined with the routine clinical genotyping performed in British Columbia for
all new \gls{HIV} infections, it is not unreasonable to suppose that the
sampled individuals (399) comprise the majority of \gls{HIV}-positive network
members. This value was the lower bound of our estimated 95\% \gls{HPD}
interval
    (\Sexpr{d1[dataset == "bctree" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "bctree" & parameter == "I", round(hpd.max.95)]}),
but it seems likely that the posterior mean of
    \Sexpr{d1[dataset == "bctree" & parameter == "I", round(mean)]}
is an overestimate.}

\add{The prevalence estimates for two \gls{MSM} populations in major Chinese
cities (MSM/Beijing and MSM/Shanghai) were 
    \Sexpr{d1[dataset == "wang2015" & parameter == "I", round(mean)]} and
    \Sexpr{d1[dataset == "li2015" & parameter == "I", round(mean)]}.
The individuals sampled for the MSM/Beijing study were recruited by following a
prospective cohort of size 2000. 179 new infections were identified in the
cohort during the study period, which is much lower than the estimated
prevalence obtained with \software{netabc}. However, the authors did not claim
to have sampled the entire sexual network. In a nationwide survey,
\textcite{wu2013hiv} estimated that there were 24,198 \gls{MSM} living in
Beijing, of whom 5.7\%, or 1379, were \gls{HIV}-infected, which is close to the
upper limit of the 95\% confidence interval of our estimate of \gls{I}
    (\Sexpr{d1[dataset == "wang2015" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "wang2015" & parameter == "I", round(hpd.max.95)]}).
The same survey estimated the size of the \gls{MSM} population in Shanghai
14,511, with an \gls{HIV} prevalence of 6.8\% or approximately 987 individuals.
This was within the 95\% confidence interval of the estimate obtained with
\software{netabc} for the MSM/Shanghai data
    (\Sexpr{d1[dataset == "li2015" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "li2015" & parameter == "I", round(hpd.max.95)]}).
It is worth noting that the authors of the IDU/Shanghai
study~\autocite{li2015hiv} claimed that there were 80,000 \gls{MSM} living in
Shanghai, which is a significantly different estimate than that obtained by
\textcite{wu2013hiv}. The authors of the MSM/Taiwan
study~\autocite{kao2011surveillance} stated that there were 18,378
\gls{HIV}-infected individuals in Taiwan, of which approximately 44\% (8086
individuals) were \gls{MSM}. This value is well outside of our 95\% \gls{HPD} 
    (\Sexpr{d1[dataset == "kao2011" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "kao2011" & parameter == "I", round(hpd.max.95)]}),
suggesting that the entire \gls{MSM} population does not comprise a single
network. In fact, our estimate of \gls{I} for these data
    (\Sexpr{d1[dataset == "kao2011" & parameter == "I", round(mean)]}),
was closer to the number of \gls{MSM} enrolled in the study (301) than to the
epidemiologically estimated prevalence. The study focused exclusively on newly
diagnosed individuals. On the other hand, our estimated prevalence for the
MSM/USA data
    (\Sexpr{d1[dataset == "little2014" & parameter == "I", round(mean)]})
was clearly an underestimate. The study enrolled almost 648 \gls{HIV}-infected 
individuals, which should have been a lower bound on \gls{I}, although the
value was contained in the 95\% \gls{HPD} interval
    (\Sexpr{d1[dataset == "little2014" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "little2014" & parameter == "I", round(hpd.max.95)]}).}

\add{The HET/Uganda, HET/Malawi, and HET/Botswana data all originated from
populations in sub-Saharan Africa, where the dominant mode of transmission is
believed to be heterosexual. The HET/Uganda study population included
1434 seropositive individuals. Since the majority of inhabitants of the study
district were enrolled in the study, it is likely that this number represents
the majority of \gls{HIV}-infected persons. Our estimate was slightly lower
    (\Sexpr{d1[dataset == "grabowski2014" & parameter == "I", round(mean)]}),
but the value 1434 was contained within the 95\% \gls{HPD} interval
    (\Sexpr{d1[dataset == "grabowski2014" & parameter == "I", round(hpd.min.95)]} -
    \Sexpr{d1[dataset == "grabowski2014" & parameter == "I", round(hpd.max.95)]}).
The HET/Malawi data represents possibly the oldest population-level \gls{HIV}
sequencing effort, carried out on samples collected for other purposes between
1981 and 1989. Every individual in the study district was sampled; among these,
a total of 200 were \gls{HIV}-positive. Although the HET/Malawi data had the
lowest estimated \gls{I} value among the heterosexual datasets, 
the posterior mean
    (\Sexpr{d1[dataset == "mccormack2002" & parameter == "I", round(mean)]}),
was much higher than this value. Due to the thorough population-level
screening, it is most likely that the posterior mean represents an
overestimate, especially considering the observed upward bias of \gls{ABC}
estimates of \gls{I} observed on simulated data (\cref{fig:abcptm2}).
It is also possible that the true sexual network extended outside the study's
geographic area to include a larger number of infected individuals. The authors
of the HET/Botswana data~\autocite{novitsky2013phylogenetic,
novitsky2014impact} estimated that there were 1731 \gls{HIV}-positive
individuals in the study area. \gls{HIV} sequences were obtained from
approximately 70\% of these individuals. The estimated prevalence we obtained
was much higher 
    (\Sexpr{d1[dataset == "novitsky2014" & parameter == "I", round(mean)]}),
with a 95\% \gls{HPD} interval spanning nearly the entire prior region. The
authors noted that the town where the study took place was located proximally
to the country's capital city, and suggested that frequent travel between the
two locations may have facilitated linking of their sexual networks. Thus, the
high estimate of \gls{I} we obtained for these data may include a larger
network component based in the capital city.}

\add{\textcite{cuevas2009hiv} reported that 620 newly infected and 1500
chronically infected patients had been sampled during the study period, for a
total of 2120. This is substantially greater than the point estimate of 
    \Sexpr{d1[dataset == "cuevas2009" & parameter == "I", round(mean)]}
we obtained with \gls{ABC}. This error may in part be due to model
misspecification -- it is highly unlikely that a mixed risk group population 
would form a single, well-connected contact network of the type generated by
the \gls{BA} model.}

\subsubsection{Modelling assumptions}

Our use of the \gls{BA} model makes several simplifying assumptions. First, we
assume homogeneity across the network with respect to node behaviour and
transmission risk. In reality, the attraction to high-degree nodes seems likely
to vary among individuals, as does their risk of transmitting or contracting
the virus. We have also assumed that all transmission risks are symmetric,
which is clearly false for all known modes of \gls{HIV} transmission, and that
infected individuals never recover but remain infectious indefinitely. These
assumptions were made for the purpose of keeping the model as simple as
possible, since this is the very first attempt to fit a contact network model
in a phylodynamic context. However, the Gillespie simulation algorithm built
into \software{netabc} can handle arbitrary transmission and removal rates
which need not be homogeneous across the network. Moreover, it is possible to
use \gls{ABC} to fit a model which relaxes some or all of these assumptions,
which may be a fruitful avenue for future investigation.  Despite the possible
misspecification, our estimates of the power law exponent $\gamma$ were within
the range of values reported in the literature (\cref{tab:gamma}), \add{and our
estimates of \gls{alpha} were in rough agreement with a previous study using
survey-based epidemiology~\autocite{de2007preferential}.}
